# SPDX-FileCopyrightText: 2020 Jens Lechtenbörger
# SPDX-License-Identifier: CC0-1.0

# CI tests for emacs-reveal
# 1. Test for reuse compatibility
# 2. Run robot framework test cases

stages:
  - build
  - test

build:
  stage: build
  image: registry.gitlab.com/oer/docker/emacs-reveal:6.3.0
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cd org-mode && make autoloads && cd ..
  script:
    - cd tests
    - emacs --batch --load elisp/publish.el
  artifacts:
    paths:
      - tests/public
    expire_in: 20 minutes
  only:
    refs:
      - master
      - merge_requests

test-reuse:
  stage: test
  image: fsfe/reuse:latest
  script:
    - reuse lint

test-robot:
  stage: test
  image:
    name: ppodgorsek/robot-framework
    entrypoint: [""]
  variables:
    ROBOT_REPORTS_DIR: "tests/public/reports"
    ROBOT_TESTS_DIR: "tests/robotframework"
  script:
    - mkdir -p /robot && cp -r tests/public /robot
    - BROWSER=firefox PRESENTATION=test.html run-tests-in-virtual-screen.sh
    - BROWSER=chrome PRESENTATION=test.html run-tests-in-virtual-screen.sh
  artifacts:
    paths:
      - tests/public
    expire_in: 1 week
  only:
    refs:
      - master
      - merge_requests
