# SPDX-FileCopyrightText: 2020 Jens Lechtenbörger
# SPDX-License-Identifier: CC0-1.0

# CI tests for emacs-reveal
# 1. Test for reuse compatibility
# 2. Run robot framework test cases

stages:
  - reuse
  - build
  - robot

test-reuse:
  stage: reuse
  image: fsfe/reuse:latest
  script:
    - reuse lint

build:
  stage: build
  image: registry.gitlab.com/oer/docker/emacs-reveal:6.3.0
  script:
    - cd tests
    - emacs --batch --load elisp/publish.el
  artifacts:
    paths:
      - tests/public
    expire_in: 20 minutes
  only:
    refs:
      - master
      - merge_requests

test-robot:
  stage: robot
  image:
    name: ppodgorsek/robot-framework
    entrypoint: [""]
  variables:
    ROBOT_REPORTS_DIR: "tests/public/reports"
    ROBOT_TESTS_DIR: "tests/robotframework"
  script:
    - mkdir -p /robot && cp -r tests/public /robot
    - BROWSER=firefox PRESENTATION=test.html run-tests-in-virtual-screen.sh
  only:
    refs:
      - master
      - merge_requests
