# Local IspellDict: de

# Copyright (C) 2018-2019 Jens Lechtenbörger
# SPDX-License-Identifier: CC-BY-SA-4.0

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="index.css" />
#+STARTUP: showeverything
#+AUTHOR: Jens Lechtenbörger
#+OPTIONS: html-style:nil
#+OPTIONS: toc:nil

Diese Datenschutzerklärung informiert über die Sammlung
personenbezogener Daten im Rahmen der Nutzung offener
Bildungsmaterialien (Open Educational Resources, OER) in Form von
HTML-Präsentationen unter der Domäne {{{website}}}.

Sie müssen keinerlei personenbezogene Daten preisgeben, um auf die OER
unter {{{website}}} zuzugreifen.  Personenbezogene Daten werden nicht
erfragt und entsprechend nicht gesammelt.  Die OER beinhalten weder
Werbung noch Tracker noch Social-Media-Plugins, und sie werden ohne
Cookies ausgeliefert.  Allerdings wird der Großteil der OER in Form von
Web-Seiten (HTML-Präsentationen) von Web-Servern ausgeliefert, die von
[[https://about.gitlab.com/][GitLab]] betrieben werden, und sehr
wahrscheinlich teilt Ihr Browser vielfältige Daten mit den Servern von
GitLab, insbesondere Ihre IP-Adresse und andere technische Details,
mit denen Sie vermutlich eindeutig identifiziert werden.  GitLab
erklärt die Verwendung dieser Daten in der
[[https://about.gitlab.com/privacy/][Privacy Policy]].

Zudem binden einige OER-Präsentationen externe Ressourcen ein
(z. B. JavaScript, Bilder, Videos), und Ihr Browser teilt seine
Charakteristika mit den Servern dieser Ressourcen.

Außerdem könnte, je nach Gesetzeslage, Ihr Internet Service Provider
(ISP) verpflichtet oder durch monetäre Anreize fehlgeleitet sein, Ihre
IP-Adresse und Ihr Surf-Verhalten aufzuzeichnen.  Darüber hinaus
wissen wir dank der
[[https://de.wikipedia.org/wiki/Globale_%C3%9Cberwachungs-_und_Spionageaff%C3%A4re][Snowden-Enhüllungen]],
dass die meisten Geheimdienste jegliche Internet-Daten sammeln, derer
sie habhaft werden können, einschließlich des Surf-Verhaltens.

Die gute Nachricht ist, dass Sie sich in keiner der obigen Arten
überwachen lassen müssen, wenn Sie das nicht wollen, besonders nicht
beim Lernen anhand von OER unter {{{website}}}, wie nachfolgend
erklärt.

Wenn Sie beim Surfen nicht überwacht werden möchten, müssen Sie
Techniken der digitalen Selbstverteidigung erlernen und anwenden.
Entsprechende Werkzeuge zum Schutz Ihrer Privatsphäre sind als
[[https://fsfe.org/about/basics/freesoftware.de.html][freie Software]]
verfügbar.  Persönlich verwende und
[[https://www.informationelle-selbstbestimmung-im-internet.de/Anonymes_Surfen_mit_Tor.html][empfehle]]
ich den
[[https://www.torproject.org/projects/torbrowser.html][Tor Browser]]
zum tagtäglichen, vor Überwachung geschützten Surfen.
Die OER unter {{{website}}} funktionieren auch unter den erhöhten
“Safer” Sicherheitseinstellungen im Tor Browser.

Alternativ können Sie die OER auch herunterladen und anschließend
lokal und offline verwenden.  Zu diesem Zweck können Sie entweder die
Ergebnisse der letzten Pipeline-Ausführung von GitLab herunterladen
oder das Repository über Git-Mechanismen kopieren und die
Präsentationen selbst erzeugen.  (Wie oben erwähnt beinhalten manche
Präsentationen Ressourcen von externen Servern; diese sind bei
Offline-Verwendung nicht verfügbar.  Wenn Sie online lernen und Ihr
Browser die Ressourcen anfragt, können diese Anfragen wieder überwacht
werden, was den Tor Browser als erste Wahl erscheinen lässt.)

Wenn Sie als eine/r
[[https://www.wi.uni-muenster.de/department/dbis/people/jens-lechtenboerger][meiner]]
Studierenden mit den OER unter {{{website}}} arbeiten und Bedenken
hinsichtlich der obigen Erklärungen haben, sprechen Sie mich bitte an.
Wenn Sie vorziehen sollten, dass Ihre Daten unter Ihrer ZIV-Kennung im
Learnweb im Einklang mit der universitären Datenschutzerklärung
verarbeitet werden, könnte ich die OER unter {{{website}}} auch im
Learnweb zur Verfügung stellen.
